version: '3'
services:
  reverse: 
    image: nginx:latest
    container_name: reverse
    hostname: reverse
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/ssl/private:/etc/ssl/private
      
  root-cpp:
    container_name: root-cpp
    hostname: root-cpp
    build:
      context: ./
      dockerfile: root/Dockerfile
    expose:
      - "8888"
    volumes:
      - ~/notebooks/:/home/polyglot/notebooks

  ihaskell:
    container_name: ihaskell
    hostname: ihaskell
    build:
      context: ./
      dockerfile: ihaskell/Dockerfile
    expose:
      - "8888"
    volumes:
      - ~/notebooks/:/home/polyglot/notebooks
